# Generated by Django 3.2 on 2021-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoclass',
            name='image',
            field=models.ImageField(blank=True, default='defualt.jpg', upload_to=''),
        ),
    ]
